name: Generate Snake

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ByteSide
          outputs: |
            dist/github-snake.svg?color_snake=#FD7D00&color_dots=#06171E,#015351,#0d9e9b,#2bc4c0,#FD7D00
            dist/github-snake-dark.svg?color_snake=#FD7D00&color_dots=#06171E,#0a3a3a,#015351,#0d9e9b,#2bc4c0

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
